repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.4.7 # use the latest stable Ruff version
      hooks:
          - id: ruff
            args: [--fix]

    - repo: https://github.com/psf/black
      rev: 23.11.0 # latest stable Black
      hooks:
          - id: black
