version: "3.9"

services:
    db:
        image: postgres:16-alpine
        container_name: app-postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${APP_DB_USER:-appuser}
            POSTGRES_PASSWORD: ${APP_DB_PASSWORD:-apppass}
            POSTGRES_DB: ${APP_DB_NAME:-appdb}
        ports:
            - "${APP_DB_PORT:-5432}:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
        healthcheck:
            test:
                ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
            interval: 5s
            timeout: 3s
            retries: 10

    # Optional admin UI for demos + screenshots
    pgadmin:
        image: dpage/pgadmin4:8
        container_name: app-pgadmin
        restart: unless-stopped
        depends_on:
            db:
                condition: service_healthy
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@example.com}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-adminpass}
        ports:
            - "5050:80"

volumes:
    db_data:
